default_install_hook_types:
  - pre-push

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: ruff check .
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: black
        name: black
        entry: black --check .
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: mypy
        name: mypy
        entry: mypy .
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: bandit
        name: bandit
        entry: bandit -c bandit.yaml -r .
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: pytest
        name: pytest
        entry: env PYTHONPATH=. pytest --cov-report=term-missing
        language: system
        pass_filenames: false
        stages: [pre-push]
