default_install_hook_types:
  - pre-push

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        entry: ruff check test main.py ga_optimizer utilis.py
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: ruff-format
        name: ruff-format
        entry: ruff format --check test main.py ga_optimizer utilis.py
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: mypy
        name: mypy
        entry: mypy --config-file pyproject.toml
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: bandit-dirs
        name: bandit-dirs
        entry: bandit -c pyproject.toml -r test ga_optimizer
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: bandit-files
        name: bandit-files
        entry: bandit -c pyproject.toml main.py utilis.py
        language: system
        pass_filenames: false
        stages: [pre-push]

      - id: pytest
        name: pytest
        entry: env PYTHONPATH=. pytest
        language: system
        pass_filenames: false
        stages: [pre-push]