import argparse
import json
import os
import wandb
import weave
from collections import Counter
from google import genai
from google.genai import types

class ScriptConfig:
    """
    Holds all modifiable parameters for the script.
    """
    # Project settings
    WANDB_PROJECT = "llmfe-feature-engineering-btc"
    WEAVE_PROJECT = "llmfe-feature-engineering-btc"

    # Model and API settings
    DEFAULT_MODEL = "gemini-2.5-flash"
    DEFAULT_TEMPERATURE = 0.2
    
    # Batching settings
    DEFAULT_MAX_PAYLOAD_CHARS = 40000


# Prompt for feature modification evaluation 
PROMPT_TEMPLATE = """
You are a strict Senior Machine Learning Engineer and Data Scientist. You are evaluating feature engineering scripts generated by an
automated system.
Your goal is to filter out hallucinated, mathematically invalid, or nonsensical features while preserving novel, high-value signals.

### INPUT CONTEXT
Dataset Description: {metadata_content}
(Note: Use this context to understand the semantic type of each column: Continuous, Ordinal, Nominal/Categorical, or Boolean.)

### EVALUATION RUBRIC
You must evaluate EVERY single feature assignment (e.g., `df['new'] = ...`) individually.

#### 1. "Makes sense" (Valid Signal)
* **Interaction Logic:** The transformation creates a meaningful interaction between compatible variables (e.g., `Price * Quantity` or `Temp - DewPoint`).
* **Non-Linearity:** Applies valid mathematical transformations (Log, Sigmoid, Power) to continuous variables to handle skew or saturation.
* **Domain Knowledge:** Encodes specific domain rules (e.g., identifying "Rush Hour" from time, or "Debt-to-Income Ratio" in finance).

#### 2. "No impact" (Redundant/Trivial)
* **Linear Redundancy:** Simple linear scaling or shifting (e.g., `x + 10`, `x * 100`) unless meaningful for a specific distance-based algorithm.
* **Monotonic Transformations:** Ranking or scaling variables that preserve order, which provides zero new information to tree-based models (e.g., `rank(sorted_variable)`).

#### 3. "Makes no sense" (CRITICAL REJECTION CRITERIA)
* **Ordinal/Categorical Magnitude Abuse (MOST COMMON ERROR):**
    * Multiplying an Ordinal/Nominal integer directly by a Continuous variable (e.g., `Category_ID * Price`). This implies an arbitrary magnitude relationship (e.g., Category 2 is "twice" Category 1) which is rarely true.
    * Multiplying an Ordinal/Nominal integer by a Binary mask. This implies "0" is a valid category on the same scale as the labels.
* **Semantic Incompatibility:**
    * Adding/Subtracting variables with incompatible units (e.g., `Age + ZipCode` or `Temperature + WindSpeed`).
* **Data Leakage:**
    * Using future information or aggregate statistics (mean/std) calculated over the entire dataset without respect to time-series splitting or train/test separation.
* **Type Errors:**
    * Applying numerical functions (Log, Sqrt) to categorical indices or ID columns.

### INSTRUCTIONS
1. **Type Inference:** For every input column used, determine if it is Continuous, Ordinal, or Categorical/Nominal.
2. **Operation Check:**
    - Continuous x Continuous = **Usually Valid** (Interaction)
    - Continuous x One-Hot (Binary) = **Valid** (Gated Interaction)
    - Continuous x Ordinal/Nominal = **INVALID** (Arbitrary Magnitude)
    - Ordinal x Ordinal = **INVALID** (Arbitrary Magnitude)
3. **Classify:** Assign strictly based on the rubric.

### PROGRAMS TO REVIEW
{data_content}

### OUTPUT FORMAT
Return ONLY a valid JSON object with this exact schema:
{{
  "review": [
    {{
      "program_index": <int>,
      "feature_name": "<name of new column>",
      "code_snippet": "<exact code line>",
      "classification": "<Makes sense | No impact | Makes no sense>",
      "reasoning": "<Concise critique. If rejected, explicitly state the variable types and the semantic error.>"
    }}
  ]
}}
"""

@weave.op()
def call_gemini_api(client, model, prompt, temperature):
    """
    Calls the Gemini API and returns a flat dictionary for Weave.
    """
    response = client.models.generate_content(
        model=model,
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=temperature
        )
    )

    input_tokens = 0
    output_tokens = 0
    total_tokens = 0
    thought_tokens = 0 

    if hasattr(response, 'usage_metadata'):
        input_tokens = response.usage_metadata.prompt_token_count
        output_tokens = response.usage_metadata.candidates_token_count
        total_tokens = response.usage_metadata.total_token_count
        
        # Check for thought_tokens, as not all models may have it
        if hasattr(response.usage_metadata, 'thoughts_token_count'):
            thought_tokens = response.usage_metadata.thoughts_token_count

    # Parse the JSON and extract the 'review' list
    review_list = []
    
    try:
        output_data = json.loads(response.text)
        # Handle if API returns a raw list or a dict
        if isinstance(output_data, list):
            review_list = output_data
        else:
            review_list = output_data.get("review", [])
            
    except Exception as e:
        print(f"Failed to parse Gemini JSON: {e}")

    # Return a flat dictionary for the Weave trace
    return {
        "review": review_list,
        "input_tokens": input_tokens,
        "output_tokens": output_tokens,
        "thought_tokens": thought_tokens,
        "total_tokens": total_tokens
    }

def process_batch(client, model, metadata_text, batch_programs_list, 
                  batch_programs_map, wandb_table, all_classifications_list, 
                  temperature):
    """
    Sends a single batch to the Gemini API and logs the results.
    Returns the feature reviews AND the score/classification pairs.
    """
    print(f"Processing batch of {len(batch_programs_list)} programs...")
    
    # Store data for the box plot
    batch_score_classification_pairs = []
    
    try:
        final_prompt = PROMPT_TEMPLATE.format(
            data_content="\n".join(batch_programs_list),
            metadata_content=metadata_text
        )
        
        api_result = call_gemini_api(client, model, final_prompt, temperature)
        
    except Exception as e:
        print(f"Gemini API Failed for this batch: {e}")
        api_result = {"review": []} # Use the same structure for failure

    feature_reviews = api_result.get("review", [])
    
    for feat in feature_reviews:
        idx = feat.get("program_index")
        
        # Get original score from the program map
        original_entry = batch_programs_map.get(idx, {})
        program_score = original_entry.get("score", 0)
        classification = feat.get("classification", "N/A")
        
        # Add data to the in-memory wandb.Table object
        wandb_table.add_data(
            idx,
            feat.get("feature_name", "Unknown"),
            classification,
            feat.get("reasoning", "N/A"),
            feat.get("code_snippet", ""),
            program_score
        )
        
        # Keep track of all classifications for the final histogram
        all_classifications_list.append(classification)
        
        # Add data for the box plot
        batch_score_classification_pairs.append([classification, program_score])
        
    print(f"Batch processed. Added {len(feature_reviews)} feature reviews.")
    
    # Return lists for backup and for the box plot
    return feature_reviews, batch_score_classification_pairs


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input_file", required=True, help="Path to the .jsonl log")
    parser.add_argument("--api_key", required=True, help="Gemini API Key")
    parser.add_argument("--wandb_run_id", required=True, help="WandB Run ID to resume")
    parser.add_argument("--metadata_path", required=True, help="Path to the metadata JSON file") 
    
    # Arguments pull defaults from the Config class
    parser.add_argument("--wandb_project", 
                        default=ScriptConfig.WANDB_PROJECT,
                        help="WandB Project")
    parser.add_argument("--model", 
                        default=ScriptConfig.DEFAULT_MODEL, 
                        help="Model version")
    parser.add_argument("--temperature", 
                        type=float, 
                        default=ScriptConfig.DEFAULT_TEMPERATURE, 
                        help="Model temperature")
    parser.add_argument("--max_payload_chars", 
                        type=int, 
                        default=ScriptConfig.DEFAULT_MAX_PAYLOAD_CHARS, 
                        help="Approx max chars of code to send in one API call")
    args = parser.parse_args()

    # Load Metadata
    metadata_text = "No metadata provided."
    if args.metadata_path and os.path.exists(args.metadata_path):
        try:
            with open(args.metadata_path, 'r') as f:
                meta_json = json.load(f)
                metadata_text = json.dumps(meta_json, indent=2)
        except Exception as e:
            print(f"Warning: Failed to load metadata from {args.metadata_path}: {e}")

    # Initialize API Client
    print(f"Initializing Client for model: {args.model}...")
    try:
        client = genai.Client(api_key=args.api_key)
    except Exception as e:
        print(f"Failed to initialize API client: {e}")
        return

    # Initialize W&B Run
    print(f"Resuming WandB Run ID: {args.wandb_run_id}...")
    try:
        # Init wandb once, and log everything at the end
        with wandb.init(project=args.wandb_project,
                        id=args.wandb_run_id, 
                        resume="must") as run:
            
            # Init Weave *inside* the successful run context
            weave.init(ScriptConfig.WEAVE_PROJECT)
            
            # Create the single table for feature analysis
            table = wandb.Table(columns=[
                "Program Index", "Feature Name", "Classification", 
                "Reasoning", "Specific Code", "Program Score"
            ])
            
            # Lists to hold results from ALL batches
            all_classifications = []
            all_reviews_list = [] # For local backup
            all_score_classification_data = [] # For box plot

            # State for the current batch
            current_batch_programs = []
            current_batch_map = {} # To store original 'score'
            current_payload_size = 0

            try:
                # Read the file line-by-line to process in batches
                with open(args.input_file, 'r') as f:
                    for i, line in enumerate(f):
                        if not line.strip():
                            continue
                            
                        entry = json.loads(line)
                        full_code = entry['generated_program']
                        
                        program_str = f"--- Program Index {i} ---\nScore: {entry['score']}\nCode:\n{full_code}\n"
                        program_size = len(program_str)

                        # Check if this program would overflow the batch
                        if (current_payload_size + program_size > args.max_payload_chars) and current_batch_programs:
                            # If yes, process the current batch
                            batch_review_list, batch_score_pairs = process_batch(
                                client, args.model, metadata_text, 
                                current_batch_programs, current_batch_map, 
                                table, all_classifications,
                                args.temperature
                            )
                            all_reviews_list.append(batch_review_list)
                            all_score_classification_data.extend(batch_score_pairs)
                            
                            # Reset for the next batch
                            current_batch_programs = []
                            current_batch_map = {}
                            current_payload_size = 0

                        # Add the current program to the new batch
                        current_batch_programs.append(program_str)
                        current_batch_map[i] = entry
                        current_payload_size += program_size

                # Process the final batch (the "leftovers")
                if current_batch_programs:
                    print("Processing final batch...")
                    batch_review_list, batch_score_pairs = process_batch(
                        client, args.model, metadata_text, 
                        current_batch_programs, current_batch_map, 
                        table, all_classifications,
                        args.temperature
                    )
                    all_reviews_list.append(batch_review_list)
                    all_score_classification_data.extend(batch_score_pairs)

            except FileNotFoundError:
                print(f"Log file not found: {args.input_file}")
                return
            except Exception as e:
                print(f"Error reading file {args.input_file}: {e}")
                return

            if not all_classifications:
                print("No features were reviewed.")
                return

            # Log the single, combined table to W&B
            print("All batches complete. Logging to WandB...")
            run.log({"Program_Evaluation/Feature_Analysis": table})
            
            # Generate and log the final histogram
            counts = Counter(all_classifications)
            bar_table = wandb.Table(columns=["Classification", "Count"])
            for category, count in counts.items():
                bar_table.add_data(category, count)
                
            run.log({
                "Program_Evaluation/Feature_Classification_Chart": wandb.plot.bar(
                    bar_table, "Classification", "Count",
                    title="Feature Alteration Classification Counts"
                )
            })
            
            if all_score_classification_data:

                box_table = wandb.Table(
                    columns=["Classification", "Score"], 
                    data=all_score_classification_data
                )
                run.log({
                    "Program_Evaluation/Score_vs_Classification_Table": box_table
                })
            
            print(f"Uploaded {len(all_classifications)} total feature reviews to WandB.")

    except Exception as e:
        print(f"WandB Upload Failed: {e}")

    # Save a combined local backup
    final_backup_json = {"review": []}
    
    for review_list in all_reviews_list:
        final_backup_json["review"].extend(review_list)

    base_name = os.path.splitext(os.path.basename(args.input_file))[0]
    review_path = os.path.join(os.path.dirname(args.input_file), f"{base_name}_review.json")
    
    with open(review_path, 'w') as f:
        json.dump(final_backup_json, f, indent=2)
    
    print(f"Local review backup saved to {review_path}")

if __name__ == "__main__":
    main()
